# Generated by Django 5.2.11 on 2026-02-16 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Include',
                'verbose_name_plural': 'Includes',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Длительность, часов')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalog/attractions/photos/', verbose_name='Фотография')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attractions', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GroupTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('group_size', models.PositiveIntegerField(verbose_name='Численность группы')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_tours', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'GroupTour',
                'verbose_name_plural': 'GroupTours',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GroupTourMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='catalog/group_tours/media/', verbose_name='Файл')),
                ('media_type', models.CharField(choices=[('image', 'Фото'), ('video', 'Видео')], max_length=10, verbose_name='Тип медиа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='tours.grouptour')),
            ],
            options={
                'verbose_name': 'Медиа GroupTour',
                'verbose_name_plural': 'Медиа GroupTour',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToursDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Длительность, часов')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalog/tours_days/photos/', verbose_name='Фотография')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tours_days', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'ToursDay',
                'verbose_name_plural': 'ToursDays',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GroupTourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1)),
                ('group_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.grouptour')),
                ('tours_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.toursday')),
            ],
            options={
                'verbose_name': 'Связь GroupTour -> ToursDay',
                'verbose_name_plural': 'Связи GroupTour -> ToursDay',
                'ordering': ['day_number', 'id'],
                'unique_together': {('group_tour', 'tours_day')},
            },
        ),
        migrations.AddField(
            model_name='grouptour',
            name='tour_days',
            field=models.ManyToManyField(blank=True, related_name='group_tours', through='tours.GroupTourDay', to='tours.toursday', verbose_name='Дни тура'),
        ),
        migrations.CreateModel(
            name='ToursDayAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.attraction')),
                ('tours_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.toursday')),
            ],
            options={
                'verbose_name': 'Связь ToursDay -> Достопримечательность',
                'verbose_name_plural': 'Связи ToursDay -> Достопримечательность',
                'ordering': ['position', 'id'],
                'unique_together': {('tours_day', 'attraction')},
            },
        ),
        migrations.AddField(
            model_name='toursday',
            name='attractions',
            field=models.ManyToManyField(blank=True, related_name='tours_days', through='tours.ToursDayAttraction', to='tours.attraction', verbose_name='Достопримечательности'),
        ),
        migrations.CreateModel(
            name='ToursDayInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('include', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.include')),
                ('tours_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.toursday')),
            ],
            options={
                'verbose_name': 'Связь ToursDay -> Include',
                'verbose_name_plural': 'Связи ToursDay -> Include',
                'ordering': ['position', 'id'],
                'unique_together': {('tours_day', 'include')},
            },
        ),
        migrations.AddField(
            model_name='toursday',
            name='includes',
            field=models.ManyToManyField(blank=True, related_name='tours_days', through='tours.ToursDayInclude', to='tours.include', verbose_name='Includes'),
        ),
    ]
