# Generated by Django 5.2.11 on 2026-02-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='include',
            name='icon_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Иконка (путь в media)'),
        ),
    ]
